from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


def create_long_prokuratura():
    c = canvas.Canvas("test_long_prokuratura.pdf", pagesize=A4)
    width, height = A4

    y = height - 50

    def write_line(text, bold=False, y_offset=20):
        nonlocal y
        if bold:
            c.setFont("Helvetica-Bold", 11)
        else:
            c.setFont("Helvetica", 10)
        if y < 50:
            c.showPage()
            y = height - 50
        c.drawString(50, y, text)
        y -= y_offset

    write_line("O'ZBEKISTON RESPUBLIKASI BOSH PROKURATURASI", bold=True)
    write_line("Iqtisodiy jinoyatlar va korrupsiyaga qarshi kurash boshqarmasi", bold=True)
    write_line("Toshkent shahri, Yunusobod tumani, Amir Temur shoh ko'chasi, 56-uy")
    write_line("Tel: +998 71 233-XX-XX | Faks: +998 71 233-XX-XX")
    write_line(" ")
    write_line("SQB (Sanoat Qurilish Bank) Aksiyadorlik Jamiyati", bold=True)
    write_line("Boshqaruv raisi janob Ergashev Akbar Akbarovich ga")
    write_line("Yuridik manzil: Toshkent sh., Shayxontohur t., Navoiy ko'chasi, 16-uy")
    write_line(" ")
    write_line("RASMIY TALAB-XATI", bold=True)
    write_line("Raqami: BP-IJ-2024/KR-8847")
    write_line("Sana: 2024-yil 28-noyabr")
    write_line("Maxfiylik darajasi: DSP (Rasmiy foydalanish uchun)")
    write_line(" ")
    write_line("HUQUQIY ASOS:", bold=True)
    write_line("O'zbekiston Respublikasi Jinoyat-protsessual kodeksining 178, 180, 214-moddalari,")
    write_line("O'zbekiston Respublikasi 'Pul yuvishga va terrorizmni moliyalashtirishga")
    write_line("qarshi kurash togrisida'gi Qonunning 12, 15-moddalari,")
    write_line("O'zbekiston Respublikasi 'Bank siri togrisida'gi Qonunning 5-moddasi asosida")
    write_line(" ")
    write_line("JINOIY ISH HAQIDA MA'LUMOT:", bold=True)
    write_line("Jinoiy ish raqami: 14-2024-IJ/KR-332")
    write_line("Ochilgan sana: 2024-yil 1-oktyabr")
    write_line("Jinoyat turi: Pul mablaglarini yuvish (O'zR JK 243-modda),")
    write_line("Mansab vakolatlaridan suiste'mol qilish (O'zR JK 205-modda),")
    write_line("Soliq tolovidan boyish (O'zR JK 184-modda)")
    write_line("Zarar miqdori: taxminan 4,750,000 AQSh dollari ekvivalenti")
    write_line(" ")
    write_line("TEKSHIRUV OBYEKTLARI:", bold=True)
    write_line("1. JISMONIY SHAXSLAR:")
    write_line("   a) Toshmatov Ulugbek Hamidovich")
    write_line("      JSHSHIR: 11223344556677")
    write_line("      Tug'ilgan sana: 1978-yil 15-mart")
    write_line("      Manzil: Toshkent sh., Chilonzor t., 12-mavze, 45-uy, 7-xonadon")
    write_line("      Lavozimi: 'Innovatsiya Plus' MChJ direktori")
    write_line("   b) Rahimova Dilnoza Akbarovna")
    write_line("      JSHSHIR: 99887766554433")
    write_line("      Tug'ilgan sana: 1985-yil 22-iyun")
    write_line("      Manzil: Toshkent sh., Mirzo Ulugbek t., Zarkaynar ko'chasi, 8-uy")
    write_line("      Lavozimi: 'FinTech Solutions' XK moliya direktori")
    write_line("   c) Karimov Jasur Murodovich")
    write_line("      JSHSHIR: 55443322110099")
    write_line("      Tug'ilgan sana: 1990-yil 3-sentyabr")
    write_line("      Lavozimi: vositachi shaxs (broker)")
    write_line(" ")
    write_line("2. YURIDIK SHAXSLAR:")
    write_line("   a) 'Innovatsiya Plus' Mas'uliyati Cheklangan Jamiyat")
    write_line("      STIR: 123456789 | DUNS: 987654321")
    write_line("      Ro'yxatdan o'tgan sana: 2019-yil 14-fevral")
    write_line("      Faoliyat turi: IT xizmatlari va konsalting")
    write_line("   b) 'Global Trade Network' Xususiy Korxona")
    write_line("      STIR: 987654321 | Bank: NBU Toshkent filiali")
    write_line("      Shubhali operatsiyalar boshlanish sanasi: 2022-yil yanvar")
    write_line("   c) 'TechVenture Capital' OF (Offshore fond)")
    write_line("      Ro'yxatdan o'tgan joy: Britaniya Virgin orollari")
    write_line("      Ishlatilgan hisob: IBAN GB29 NWBK 6016 1331 9268 19")
    write_line(" ")
    write_line("SO'RALAYOTGAN MA'LUMOTLAR ROYXATI:", bold=True)
    write_line("I. BANK HISOBVARAQLARI BO'YICHA:")
    write_line("   1. Yuqorida keltirilgan barcha shaxs va tashkilotlarning")
    write_line("      2020-yil 1-yanvardan 2024-yil 1-noyabrgacha bo'lgan")
    write_line("      barcha bank hisobvaraqlarining to'liq ro'yxati")
    write_line("   2. Har bir hisobvaraq bo'yicha: ochilgan sana, yopilgan sana (agar yopilgan bo'lsa),")
    write_line("      joriy qoldiq, maksimal qoldiq va minimal qoldiq")
    write_line("   3. Hisobvaraqqa bog'liq barcha vakolatli shaxslar ro'yxati")
    write_line(" ")
    write_line("II. TRANZAKSIYALAR BO'YICHA:")
    write_line("   1. 10,000,000 so'm (yoki ekvivalent) dan yuqori barcha operatsiyalar")
    write_line("   2. Xorijiy valyutadagi (USD, EUR, GBP, CHF) barcha o'tkazmalar")
    write_line("   3. Offshor hisoblarga (BVI, Cayman Islands, Panama) barcha o'tkazmalar")
    write_line("   4. Naqd pul operatsiyalari (kirim va chiqim) 5,000,000 so'mdan yuqori")
    write_line("   5. Bir kunda bir nechta kichik summadagi o'tkazmalar (smurfing belgisi)")
    write_line(" ")
    write_line("III. ICHKI BANK HUJJATLARI BO'YICHA:")
    write_line("   1. Ushbu shaxslar bo'yicha KYC (Mijozni bilish) hujjatlari")
    write_line("   2. AML (Pul yuvishga qarshi) bo'yicha ichki tekshiruv natijalari")
    write_line("   3. Shubhali operatsiyalar bo'yicha Moliyaviy razvedka qo'mitasiga")
    write_line("      yuborilgan xabarnomalar (STR - Suspicious Transaction Report)")
    write_line("   4. Kredit tarixi va kredit qarorlari")
    write_line("   5. Kafillik va garov hujjatlari")
    write_line(" ")
    write_line("MAXSUS TALABLAR:", bold=True)
    write_line("1. Barcha hujjatlar notarial tasdiqlangan nusxada taqdim etilishi shart")
    write_line("2. Elektron formatda ham taqdim etish (CD yoki shifrlangan USB)")
    write_line("3. Hujjatlarni taqdim etgan xodimning F.I.Sh va lavozimi ko'rsatilishi shart")
    write_line("4. Ushbu so'rovni HECH KIMGA oshkor qilmaslik - jinoiy javobgarlik")
    write_line("5. Hujjatlarni yo'q qilish yoki o'zgartirish taqiqlanadi - 8 yil qamoq")
    write_line(" ")
    write_line("JAVOB MUDDATI: 2024-yil 5-dekabr (3 ish kuni)", bold=True)
    write_line("OGOHLANTIRISH: Muddatni buzish 200 BHM miqdorida jarima", bold=True)
    write_line(" ")
    write_line("Bosh prokuror o'rinbosari, davlat adolat maslahatchisi 2-sinfi")
    write_line("Xolmatov Rustam Salimovich")
    write_line("Imzo: ___________________  Muhr")
    write_line(" ")
    write_line("Ijrochi: Tergov bo'limi katta tergovchisi Nazarov B.K.")
    write_line("Tel: +998 71 233-XX-XX (ichki: 247)")

    c.save()
    print("✅ test_long_prokuratura.pdf yaratildi!")


create_long_prokuratura()